- readme.md
**https://github.com/transpiling/svelte-flat-ui**
**This is a svelte flat-ui components**
<br>
> add Components section and svelte-flat-ui

- readme.md
**https://github.com/ekhaled/svelte-hot-loader**
**Allows svelte components to be re-rendered in place when source file changes**
<br>
> Add svelte-hot-loader

- readme.md
https://framagit.org/eraviart/vitrine
Vitrine is an application that generates dynamically the landing pages of a web site using documents & data retrieved from other sites (using their APIs). - Built with Sapper.
<br>
> Just found this project. Quite extensive.

- readme.md
https://github.com/antony/svelte-seed
https://github.com/antony/svelte-box
Seeds for starting:
a) a basic svelte app with Parcel
b) an Ethereum dApp for the blockchain using Svelte + Parcel.
<br>
> Add a couple of my seeds that I use

- readme.md
Added WebStorm plugin:
https://plugins.jetbrains.com/plugin/12375-svelte
https://github.com/tomblachut/svelte-intellij
> Added WebStorm plugin

- readme.md
**https://packagecontrol.io/packages/Svelte**
**Sublime Text Svelte Syntax Highlighting**
> Add Sublime Text syntax

- readme.md
These plugins haven't been updated in the past three years
> Remove unmaintained plugins

- readme.md
**https://github.com/kaisermann/svelte-preprocess**
**The most popular svelte preprocessor according to GitHub stars and forks. Supports numerous languages/technologies.**
<br>
By submitting this pull request, I promise I have read the [contribution guidelines](/../contributing.md) twice and ensured my submission follows it. - NOTE: this link is broken. I guess it should point to https://github.com/sveltejs/svelte/blob/master/CONTRIBUTING.md?
> Add svelte-preprocess

- readme.md
https://github.com/leafOfTree/vim-svelte-plugin
A Vim syntax and indent plugin for `.svelte` files. It is helpful if you want to write Svelte in vim.
> Add vim-svelte-plugin

- readme.md
**[Insert URL to the item here.]**
**[Explain what this item is about and why it should be included here.]**
<br>
> Added tempaltes section

- readme.md
**https://github.com/tretapey/svelte-pwa**
**SvelteJS PWA starte template based in the official one**
<br>
> Add PWA starter template

- readme.md
Starting with these entries:
**[sapper-template#rollup](https://github.com/sveltejs/sapper-template/tree/rollup)**
**[sapper-template#webpack](https://github.com/sveltejs/sapper-template/tree/webpack)**
**[sapper-firebase-typescript-graphql-tailwindcss-actions-template](https://github.com/babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template)**
**[sapper-mdsvex-template](https://github.com/pngwn/sapper-mdsvex-template)**
**[sapper-mdsvex-template-webpack](https://github.com/shiryel/sapper-mdsvex-template-webpack)**
**[sapper-postcss-template](https://github.com/babichjacob/sapper-postcss-template)**
**[sapper-tailwindcss-template](https://github.com/sarioglu/sapper-tailwindcss-template)**
**[sapper-template-firebase](https://github.com/nhristov/sapper-template-firebas …
> Add maintained Sapper templates

- readme.md
**[https://github.com/toerndev/svelte-ts-eslint-tailwind]**
**[There is no similar boilerplate that isn't for Sapper, and the README explores the combinations of ESLint + TS, and Rollup + Tailwind CSS which can be tricky.]**
<br>
> Add svelte-ts-eslint-tailwind boilerplate

- readme.md
**[https://github.com/NicoCevallos/svelte-template]**
**[Boilerplate template with TypeScript support activated and ESLint and Prettier configured and working together through eslint-plugin-prettier linting and formatting svelte files with or without TS code]**
<br>
> svelte-ts-eslint-prettier-template

- readme.md
**[https://github.com/SyntaxRules/svelte-flask](https://github.com/SyntaxRules/svelte-flask)**
**A template that utilizes python's flask webserver/api to serve built svelte pages.**
<br>
> Add svelte-flask

- readme.md
**[https://github.com/tommywalkie/sapper-typescript-esbuild-template](https://github.com/tommywalkie/sapper-typescript-esbuild-template)**
**This is a minimal Sapper template including ESBuild, TypeScript,** `svelte-check` **and** `svelte-preprocess`
> Added sapper-typescript-esbuild-template

- readme.md
**https://github.com/manuel3108/svelte-bulma-template**
**Tempalte with [Bulma](https://bulma.io/) configured.**
<br>
> Template with Bulma

- readme.md
Svite is a wrapper around `vite` a native ESM powered tool.
**https://github.com/dominikg/svite**
**svite wraps around a native ESM bundler vite that enables development to happing without having to recompile everything, and includes hmr. Easy to get started with Svelte **
<br>
> Added Svite to templates

- readme.md
**https://github.com/Zimtir/SENT-template**
**Description of SENT-template not contain enough information about provided features like in others tools**
<br>
> Update description of SENT-template

- readme.md
https://github.com/navneetsharmaui/sveltekit-starter
**SvelteKit Starter template with Typescript, Postcss, scss, TailwindCSS, Storybook, husky, eslint and Scalable project structure already setup. User will just need to use this starter template and they will get all the setup done for them.**
> Added the sveltkit starter template

- readme.md
Add [srmullen/sveltekit-stripe](https://github.com/srmullen/sveltekit-stripe) to list.
> Added sveltekit-stripe template

- readme.md
**[Insert URL to the item here.]**
**[Explain what this item is about and why it should be included here.]**
<br>
> Add SvelteNova to Editor-extensions section
